[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook_whitelist = "AM12uJDtCRDa5ENz1GM3ffqz6XZm3Ea2AW12GeEdB2Ti"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
